// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLS2CdbZHdTat22ZDmcU3sC0yYoiXsuto',
    appId: '1:895053601938:web:a2e2f8a7489d3ad93f9a4b',
    messagingSenderId: '895053601938',
    projectId: 'proyek-mcs-c23ac',
    authDomain: 'proyek-mcs-c23ac.firebaseapp.com',
    databaseURL: 'https://proyek-mcs-c23ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyek-mcs-c23ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnlCAsBsrKbSZr03SRDLSp2dxQ2pzeZ1o',
    appId: '1:895053601938:android:23cbe6b213c9ccaa3f9a4b',
    messagingSenderId: '895053601938',
    projectId: 'proyek-mcs-c23ac',
    databaseURL: 'https://proyek-mcs-c23ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyek-mcs-c23ac.firebasestorage.app',
  );
}
